name: host-process-scratch-image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: build image
        run: |
          .\New-ScratchImage.ps1
      - name: push image
        if: ${{ github.event_name != 'pull_request' }}
        shell: cmd
        run: |
          docker image load -i build\host-process-scratch.tar
          set /p image_id=< build\image-id.txt
          docker image tag %image_id% ghcr.io/marosset/host-process-scratch-image:latest
          docker image push ghcr.io/marosset/host-process-scratch-image:latest
